In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('/content/Ch2_Q17_V10_Data_File.xlsx')

In [3]:
df.describe()

         Purchase         Age  Unnamed: 3
count  600.000000  600.000000         0.0
mean   300.500000    0.678333         NaN
std    173.349358    0.467506         NaN
min      1.000000    0.000000         NaN
25%    150.750000    0.000000         NaN
50%    300.500000    1.000000         NaN
75%    450.250000    1.000000         NaN
max    600.000000    1.000000         NaN

In [4]:
df.dropna()

Empty DataFrame
Columns: [Purchase, Age, Brabd, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6, Unnamed: 7]
Index: []

In [5]:
df_cleaned=df.dropna()

In [6]:
df.describe

<bound method NDFrame.describe of      Purchase  Age Brabd  Unnamed: 3  \
0           1    1     A         NaN
1           2    1     C         NaN
2           3    0     A         NaN
3           4    1     B         NaN
4           5    0     C         NaN
..        ...  ...   ...         ...
595       596    1     A         NaN
596       597    1     C         NaN
597       598    1     B         NaN
598       599    0     C         NaN
599       600    0     B         NaN

                                            Unnamed: 4 Unnamed: 5 Unnamed: 6  \
0                                                  NaN        NaN        NaN
1    A researcher at a marketing firm examines whet...        NaN        NaN
2                                                  NaN        NaN        NaN
3                                                  NaN   Purchase        Age
4                                                  NaN          1          1
..                                                 ...        ...        ...
595                                                NaN        NaN        NaN
596                                                NaN        NaN        NaN
597                                                NaN        NaN        NaN
598                                                NaN        NaN        NaN
599                                                NaN        NaN        NaN

    Unnamed: 7
0          NaN
1          NaN
2          NaN
3        Brand
4            A
..         ...
595        NaN
596        NaN
597        NaN
598        NaN
599        NaN

[600 rows x 8 columns]>

In [9]:
#a-1. Construct a contingency table that cross-classifies the data by Age and Brand. Provide the frequencies in the accompanying table.
contingency_table = pd.crosstab(df['Age'], df['Brabd'])
print(contingency_table)

Brabd    A    B   C
Age
0       52   72  69
1      176  143  88

In [13]:
#a-2. How many of the purchases were for Brand A?
num_purchases_brand_a = df['Brabd'].value_counts()['A']
print(num_purchases_brand_a)

228

In [ ]:
#b-1. Given that the customer was younger than 35 years old, what is the likelihood that the customer purchased Brand A? (Report the proportion rounded to 2 decimal places.)

In [ ]:
#b-3. Given that the customer was younger than 35 years old, what is the likelihood that the customer purchased Brand C? (Report the proportion rounded to 2 decimal places.)