In [2]:
import pandas as pd

In [3]:
df=pd.read_excel("Ch1_Q20_V12_Data_File (1).xlsx")

In [12]:
df.describe()

,Observation,x1,x2,x3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 9,Unnamed: 12,Unnamed: 13
count,91.00000,90.000000,88.000000,86.000000,0.0,0.0,0.0,6.000000,3.0,0.0
mean,46.00000,22.244444,516.977273,147.034884,NaN,NaN,NaN,223.500000,3.0,NaN
std,26.41338,9.922521,276.498175,26.143247,NaN,NaN,NaN,376.547872,2.0,NaN
min,1.00000,2.000000,37.000000,94.000000,NaN,NaN,NaN,2.000000,1.0,NaN
25%,23.50000,15.000000,258.500000,130.000000,NaN,NaN,NaN,58.250000,2.0,NaN
50%,46.00000,22.000000,555.000000,145.000000,NaN,NaN,NaN,82.500000,3.0,NaN
75%,68.50000,27.000000,741.000000,161.500000,NaN,NaN,NaN,123.250000,4.0,NaN
max,91.00000,57.000000,999.000000,213.000000,NaN,NaN,NaN,987.000000,5.0,NaN

In [4]:
df.shape

(91, 15)

In [5]:
df.dropna()

Empty DataFrame
Columns: [Observation, x1, x2, x3, Unnamed: 4, Unnamed: 5, Unnamed: 6, Unnamed: 7, Unnamed: 8, Unnamed: 9, Unnamed: 10, Unnamed: 11, Unnamed: 12, Unnamed: 13, Unnamed: 14]
Index: []

In [6]:
df.dropna().shape

(0, 15)

In [7]:
df_cleaned=df.dropna()

In [8]:
df_cleaned.shape

(0, 15)

In [9]:
df_cleaned.describe()

,Observation,x1,x2,x3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 9,Unnamed: 12,Unnamed: 13
count,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df.describe()

,Observation,x1,x2,x3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 9,Unnamed: 12,Unnamed: 13
count,91.00000,90.000000,88.000000,86.000000,0.0,0.0,0.0,6.000000,3.0,0.0
mean,46.00000,22.244444,516.977273,147.034884,NaN,NaN,NaN,223.500000,3.0,NaN
std,26.41338,9.922521,276.498175,26.143247,NaN,NaN,NaN,376.547872,2.0,NaN
min,1.00000,2.000000,37.000000,94.000000,NaN,NaN,NaN,2.000000,1.0,NaN
25%,23.50000,15.000000,258.500000,130.000000,NaN,NaN,NaN,58.250000,2.0,NaN
50%,46.00000,22.000000,555.000000,145.000000,NaN,NaN,NaN,82.500000,3.0,NaN
75%,68.50000,27.000000,741.000000,161.500000,NaN,NaN,NaN,123.250000,4.0,NaN
max,91.00000,57.000000,999.000000,213.000000,NaN,NaN,NaN,987.000000,5.0,NaN

In [14]:
#How many observation have x1 value greater than 30?
print(df[df['x1'] > 30].shape[0])

17

In [17]:
#b. Sort the data by x1 in ascending order. What are the x1, x2, and x3 values of the first observation after the data are sorted?
df1 = df.sort_values(by=['x1'],ascending=True)
print(df1.iloc[0,:])

Observation       51
x1               2.0
x2             335.0
x3             166.0
Unnamed: 4       NaN
Unnamed: 5       NaN
Unnamed: 6       NaN
Unnamed: 7       NaN
Unnamed: 8       NaN
Unnamed: 9       NaN
Unnamed: 10      NaN
Unnamed: 11      NaN
Unnamed: 12      NaN
Unnamed: 13      NaN
Unnamed: 14      NaN
Name: 50, dtype: object

In [20]:
#c. Sort the data by x1 in descending order. What are the x1, x2, and x3 values of the first observation after the data are sorted?
df2 = df.sort_values(by=['x1'],ascending=False)
print(df2.iloc[0,:])

Observation       70
x1              57.0
x2             218.0
x3             154.0
Unnamed: 4       NaN
Unnamed: 5       NaN
Unnamed: 6       NaN
Unnamed: 7       NaN
Unnamed: 8       NaN
Unnamed: 9       NaN
Unnamed: 10      NaN
Unnamed: 11      NaN
Unnamed: 12      NaN
Unnamed: 13      NaN
Unnamed: 14      NaN
Name: 69, dtype: object

In [21]:
#d. How many missing values are there in x1, x2, and x3?
print(df.isna().sum())

Observation     0
x1              1
x2              3
x3              5
Unnamed: 4     91
Unnamed: 5     91
Unnamed: 6     91
Unnamed: 7     75
Unnamed: 8     85
Unnamed: 9     85
Unnamed: 10    90
Unnamed: 11    86
Unnamed: 12    88
Unnamed: 13    91
Unnamed: 14    88
dtype: int64